### ISSUE TITLE
Pronome this

### ISSUE THREAD

**Issue by carlosbazilio** [cassianodess/Manipular_Datas#2]
https://github.com/cassianodess/Manipular_Datas/blob/cb856da354d34197c0ed7cc4f4e18fc3c230ff4d/ManipulaDatas%20-%20Java/MinhaData.java#L7

Uso do pronome this dentro de um construtor para chamar um método da classe não era possível há um tempinho atrás. Talvez isso não valha mais, mas é bom dar uma verificada.

**Comment by cassianodess** [comment]
Vou seguir o que o senhor falou, até mesmo por questão de costume, já que outras linguagens pode não aceitar.
